### ISSUE TITLE
The output format in document doesn't correspond with exmaples

### ISSUE THREAD

**Issue by Seth2482** [ensomnia16/CS305-23S-Assignment2#4]
![image](https://user-images.githubusercontent.com/22097951/234216891-f1b699cb-830c-4085-ad13-d1c77c0d6d12.png)
![image](https://user-images.githubusercontent.com/22097951/234216935-b9ba8a1c-36e2-4127-903c-cff88a7d0a20.png)

**Comment by ensomnia16** [comment]
Please refer to the example file, the documentation will be updated with relevant content immediately.
